### ISSUE TITLE
issues building

### ISSUE THREAD

**Issue by dandante** [catfact/mlp#1]
Hi,

I'm not much of a C++ developer.

I cloned the repo, git `git submodule init && git submodule update` then `cmake .  && make`. I first got an error about a missing rtaudio header, so I cloned https://github.com/thestk/rtaudio into `mlp/extern` and ran `cmake . && make` again and now I am getting:

```
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/dtenenba/dev/mlp/mlp
[ 80%] Built target oscpack
[ 90%] Building CXX object CMakeFiles/mlp-cli.dir/src/mlp-cli/main.cpp.o
/Users/dtenenba/dev/mlp/mlp/src/mlp-cli/main.cpp:108:14: error: unknown type name 'RtAudioError'; did you mean 'RtAudioErrorType'?
    } catch (RtAudioError &e) {
             ^~~~~~~~~~~~
             RtAudioErrorType
/Users/dtenenba/dev/mlp/mlp/extern/rtaudio/RtAudio.h:228:6: note: 'RtAudioErrorType' declared here
enum RtAudioErrorType {
     ^
/Users/dtenenba/dev/mlp/mlp/src/mlp-cli/main.cpp:110:10: error: member reference base type 'RtAudioErrorType' is not a structure or union
        e.printMessage();
        ~^~~~~~~~~~~~~
2 errors generated.
make[2]: *** [CMakeFiles/mlp-cli.dir/src/mlp-cli/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/mlp-cli.dir/all] Error 2
make: *** [all] Error 2
```

Do you have any suggestions? This is on an M1 Mac.
Thank you.

**Comment by catfact** [comment]
sorry i should add dependencies / build instructions. i'm doing this quickly, it's early stages, and dependencies are likely to change, so i'm not spending time on that aspect yet.

but for you, my advice would be:

- i believe you need `git submodule update --init` to actually clone the submodules (which are `oscpack` and `readerwriterqueue`. also note that `oscpack` is my fork, with a fix for m1 machines.) 

- but, `rtaudio` is not actually built by this project or included in the submodules, it is expected to be installed by the system. on mac, i personally use [macports](https://www.macports.org/) and install it with `sudo port install rtaudio`, but you should also be able to use homebrew, or build and install it manually, or whatever. 

the `CMakeLists.txt` specifies the header and library locations that macports uses. (`/opt/local/...`). so that works for me. but it also looks in `/usr/local/...`, which would be another common install location. (does homebrew use it? i can't remember.) anyway you may have to add other paths if you've set up your system differently.

- i don't know if that cmake invocation will work. depends on your system. for contemporary cmake, an all-around better way IMHO would be like so:

- navigate to the directory containing CMakeLists.txt:
`cd ~/code/mlp/mlp`

- make build directory:
`mkdir build`

- tell cmake to generate the project files under `build/`:
`cmake -S . -B build`

- tell cmake to build the project:
`cmake --build build`

**Comment by catfact** [comment]
aaanyways, i shall also just add a compiled executable to the releases page. this will be built on mac m1 / sonoma 14.5. let me know if it works for you.

**Comment by catfact** [comment]
https://github.com/catfact/mlp/releases/tag/v0.0.0

i've attached a build, but it isn't codesigned, so i'm not sure what security-disabling shenanigans would be needed to run it. (i'll get it set up the right way ASAP.)

**Comment by catfact** [comment]
... sorry, that didn't work at all. code signing is an issue (though i was able to work around it with [these steps](https://openecoacoustics.org/resources/help-centre/software/unsigned/)), but i also need to change how rtaudio is linked or distributed.

i'll work on it a bit today

**Comment by catfact** [comment]
release seems fixed to me now

**Comment by dandante** [comment]
Thank you for the binary! It appears to work - have not tried it with audio or OSC yet, but it runs and prints out stuff.

If you plan to continue making binary releases I'll just use those. If not I might try and keep up with what sound like rapid updates. I did run into some problems and wrote them up before I noticed your subsequent comments & the binary. Feel free to ignore them for now.

-------

Thanks, I appreciate the detailed instructions. I installed rtaudio with brew and made the following change:

```diff
diff --git a/mlp/CMakeLists.txt b/mlp/CMakeLists.txt
index 63552e6..0c0e5cb 100644
--- a/mlp/CMakeLists.txt
+++ b/mlp/CMakeLists.txt
@@ -4,8 +4,8 @@ project(mlp)
 set(CMAKE_CXX_STANDARD 17)

 set(INCLUDE_DIRS_LOCAL src src/mlp-cli src/mlp extern extern/oscpack)
-set(INCLUDE_DIRS_SYSTEM /opt/local/include /usr/local/include)
-set(LINK_DIRS /opt/local/lib /usr/local/lib)
+set(INCLUDE_DIRS_SYSTEM /opt/local/include /usr/local/include /opt/homebrew/include)
+set(LINK_DIRS /opt/local/lib /usr/local/lib /opt/homebrew/lib)

 IF(WIN32)
     set(IpSystemTypePath ip/win32)

```

I also removed the rtaudio clone from mlp/mlp/extern. I ran `git submodule update --init` in the root of the clone. Then I followed your instructions and got this. I wonder if there's an issue with the version of rtaudio that I ended up with (6.0.1). At least it appears to be finding the header file now.

```
❯ cmake --build build
[ 80%] Built target oscpack
[ 90%] Building CXX object CMakeFiles/mlp-cli.dir/src/mlp-cli/main.cpp.o
/Users/dtenenba/dev/mlp/mlp/src/mlp-cli/main.cpp:108:14: error: unknown type name 'RtAudioError'; did you mean 'RtAudioErrorType'?
    } catch (RtAudioError &e) {
             ^~~~~~~~~~~~
             RtAudioErrorType
/opt/homebrew/include/rtaudio/RtAudio.h:228:6: note: 'RtAudioErrorType' declared here
enum RtAudioErrorType {
     ^
/Users/dtenenba/dev/mlp/mlp/src/mlp-cli/main.cpp:110:10: error: member reference base type 'RtAudioErrorType' is not a structure or union
        e.printMessage();
        ~^~~~~~~~~~~~~
2 errors generated.
make[2]: *** [CMakeFiles/mlp-cli.dir/src/mlp-cli/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/mlp-cli.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by catfact** [comment]
Yes I think that's an api mismatch, I encountered it too at one point

In order to make a self contained binary, I ended up in fact adding rtaudio as a submodule so could be built as a static library. 

So if you pull latest and update submodules, then cmake should take care of everything

**Comment by dandante** [comment]
That worked!

I got some warnings but the executable seems to work (again, no audio or osc testing yet but I will do that soon).

Really appreciate the help.
